Jawaaf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('qna/', include('qna_app.urls')),
    path('user/', include('user_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna_app/urls.py
from django.urls import path
from qna_app import views
app_name = 'qna'

urlpatterns = [
    path('read/', views.questionlist, name='read'),
    path('popular/', views.popular),
    path('add/', views.addquestion, name='add'),
    path('update/<int:id>/', views.update_question, name='update'),
    path('delete/<int:id>/', views.delete_question, name='delete'),
    path('vote/<int:id>/', views.vote_question, name='vote_qn'),
    path('ans/<int:id>/', views.answer, name='answer'),
    path('submit/<int:id>/', views.submit, name='submit'),
    path('detail/<int:id>/', views.detail, name='qna.detail'),
    # path('listview/', views.QuestionListViews.as_view(), name='qnlist'),
]

user_app/urls.py
from django.urls import path
from user_app import views
app_name = 'user'

urlpatterns = [
    path('login/', views.loginauth, name='login'),
    path('logout/', views.logout, name='logout'),
]

qna_app/models.py
from django.db import models

# Create your models here.


class CategoryModel(models.Model):
    title = models.CharField(max_length=255)
    cat_desc = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class QuestionModel(models.Model):
    title = models.CharField(max_length=255)
    posted_by = models.CharField(max_length=120)
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    question_desc = models.TextField()
    question_votes = models.IntegerField(default=0)
    question_img = models.ImageField(upload_to='QuestionImg', blank=True, null=True)

    def __str__(self):
        return self.title


class AnswerModel(models.Model):
    answered_by = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    answer_desc = models.TextField()
    answer_votes = models.IntegerField(default=0)
    answer_img = models.ImageField(upload_to='AnswerImg', blank=True, null=True)
    is_accepted = models.BooleanField(default=0)
    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer_desc[:15] + "..."

user_app/models.py
from django.db import models


class UserModel(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)
    karma = models.PositiveIntegerField(default=0)
    contact = models.PositiveIntegerField(default=0)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name

qna_app/forms.py
from django import forms
from .models import QuestionModel, AnswerModel


class QuestionForm(forms.ModelForm):
    class Meta:
        model = QuestionModel
        fields = '__all__'


class AnswerForm(forms.ModelForm):
    class Meta:
        model = AnswerModel
        fields = '__all__'

qna_app/views.py
from django.shortcuts import render, redirect
from .models import QuestionModel, CategoryModel, AnswerModel
from .forms import QuestionForm, AnswerForm
from django.http import HttpResponse

# Create your views here.


def questionlist(request):
    if 'id' in request.session:
        questions = QuestionModel.objects.all()
        questions_dict = {'questions': questions}
        return render(request, 'questionmodel_list.html', questions_dict)
    else:
        return redirect('user:login')


def popular(request):
    questions = QuestionModel.objects.filter(question_votes__gt=2)
    questions_dict = {'questions': questions}
    return render(request, 'popular.html', questions_dict)


def addquestion(request):
    if request.method == "POST":
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('qna:read')
            except:
                return HttpResponse('Failed')
        else:
            print(form.errors)
            return HttpResponse('Form not Valid!')
    else:
        category = CategoryModel.objects.all
        return render(request, 'questionmodel_create.html', {'categories': category})


def update_question(request, id):
    question = QuestionModel.objects.get(id=id)
    if request.method == "POST":
        form = QuestionForm(request.POST, request.FILES, instance=question)
        if form.is_valid():
            try:
                form.save()
                return redirect('qna:read')
            except:
                return HttpResponse('Failed')
        else:
            print(form.errors)
            return HttpResponse('Form not Valid!')
    else:
        form = QuestionForm(instance=question)
        return render(request, 'questionmodel_update.html', {'form': form})


def delete_question(request, id):
    question = QuestionModel.objects.get(id=id)
    question.delete()
    return redirect('qna:read')


def vote_question(request, id):
    question = QuestionModel.objects.get(id=id)
    question.question_votes += 1
    question.save()
    return redirect('qna:read')


def answer(request, id):
    if request.method == "POST":
        by = request.POST.get('answered_by')
        desc = request.POST.get('answer_desc')
        answer_img = request.POST.get('answer_img')
        question = QuestionModel.objects.get(id=id)
        Comment = AnswerModel(answered_by=by, answer_desc=desc,
                              answer_img=answer_img, question=question)
        Comment.save()
        return redirect('qna:read')
    else:
        form = AnswerForm
        a = {'form': form}
        b = {'id': id}
        c = {**a, **b}
        return render(request, 'answermodel_create.html', c)


def submit(request, id):
    if request.method == "POST":
        question = QuestionModel.objects.get(id=id)
        answer = request.POST.get('answer_desc')
        Comment = AnswerModel(question=question, answer_desc=answer)
        Comment.save()
        return redirect('qna:read')


def detail(request, id):
    return render(request, 'detail.html')

# class QuestionListViews(ListView):
#     queryset = QuestionModel.objects.all()

user_app/views.py
from django.shortcuts import render, redirect
from .models import UserModel
from django.http import HttpResponse


def loginauth(request):
    if request.method == "POST":
        email = request.POST.get('email')
        code = request.POST.get('pass')
        user = UserModel.objects.filter(email=email, password=code)
        if user.count() > 0:
            validuser = user[0]
            request.session['email'] = validuser.email
            request.session['id'] = validuser.id
            request.session['name'] = validuser.name
            return redirect('qna:read')
        else:
            return HttpResponse("Wrong Credentials.")

    else:
        return render(request, 'login.html')


def logout(request):
    request.session.flush()
    return redirect('user:login')

qna_app/templates/answermodel_create.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <form class="" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            Name: <input type="text" name="answered_by" value=""><br><br>
            Answer: <input type="text" name="answer_desc" value=""><br><br>
            Image: <input type="file" name="answer_img" value=""><br><br>
            <input type="hidden" name="answer_votes" value=0>
            <input type="submit" name="" value="submit">
        </form>
    </body>
</html>

qna_app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>
        {% block title %}
            Hello, World!
        {% endblock %}
    </title>
  </head>
  <body>
      <div class="pb-2 mt-4 mb-2 border-bottom">
                    <h1>Jawaaf</h1>
                    <h6>Where you get your answers.</h6>
                    {%if 'id' in request.session%}
                      <h6>Welcome, {{request.session.name}}! |<a href="{%  url 'user:logout' %}">Log Out</a></h6>
                    {%endif%}
            </div>
    {% block main_content %}
        <h1>Hello, World</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

qna_app/templates/detail.html
{%extends "base.html"%}

{% block title %}
    Question Details
{% endblock %}

{% block main_content %}
    This is the question details
{% endblock %}

qna_app/templates/popular.html
<html lang="en" dir="ltr">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="utf-8">
    <title></title>
</head>
<body>
    {% for question in questions %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="../../media/{{question.question_img}}" class="card-img" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{question.title}}</h5>
                    <h6 class="card-category">{{question.category}}</h6>
                    <p class="card-text">{{question.question_desc|truncatechars:20}}</p>
                    <p class="card-text"><small class="text-muted">{{question.timestamp|date:'Y-M-D  h-m-s P'}}</small></p>
                    <p class="card-text"><small class="text-muted">{{question.posted_by}}</small></p>
                    <p class="card-text"><small class="text-muted"><b>Votes:</b> {{question.question_votes}}</small></p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

qna_app/templates/qna_app/questionmodel_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        {{object_list}}
    </body>
</html>

qna_app/templates/questionmodel_create.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <form class="" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            Title: <input type="text" name="title" value=""><br><br>
            Posted By: <input type="text" name="posted_by" value=""><br><br>
            Category: <select class="" name="category">
                        {% for category in categories %}
                            <option value="{{category.id}}">{{category.title}}</option>
                        {% endfor %}
                    </select> <br><br>
            Question Description: <input type="text" name="question_desc" value=""><br><br>
            Image: <input type="file" name="question_img" value=""><br><br>
            <input type="hidden" name="question_votes" value=0>
            <input type="submit" name="" value="submit">
        </form>
    </body>
</html>

qna_app/templates/questionmodel_list.html
{% extends 'base.html' %}
        {% block main_content%}
        <a href="{% url 'qna:add' %}"><button>Add</button></a>
        {% for question in questions %}
        <div class="card mb-3" style="max-width: 100%;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="../../media/{{question.question_img}}" class="card-img" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{question.title}}</h5>
                        <h6 class="card-category">{{question.category}}</h6>
                        <p class="card-text">{{question.question_desc|truncatechars:20}}</p>
                        <p class="card-text"><small class="text-muted">{{question.timestamp|date:'Y-M-D  h-m-s P'}}</small></p>
                        <p class="card-text"><small class="text-muted">{{question.posted_by}}</small></p>
                        <p class="card-text"><small class="text-muted"><b>Votes:</b> {{question.question_votes}}</small></p>

                        <form action="{% url 'qna:submit' question.id %}" method="post">
                            {% csrf_token %}
                            <textarea name="answer_desc" cols="90" rows="6">
                                    Enter some text...
                            </textarea>
                            <br>
                            <input type="submit" value='Submit'/>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'qna:update' question.id %}"><button>Update</button></a>
        <a href="{% url 'qna:delete' question.id %}"><button>Delete</button></a>
        <a href="{% url 'qna:vote_qn' question.id %}"><button>Vote</button></a>
        <a href="{% url 'qna:answer' question.id %}"><button>Answer</button></a>

        {% endfor %}
        {% endblock %}

qna_app/templates/questionmodel_update.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <form class="" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            Title: <input type="text" name="title" value=""><br><br>
            Posted By: <input type="text" name="posted_by" value=""><br><br>
            Category: <select class="" name="category">
                        {% for category in categories %}
                            <option value="{{category.id}}">{{category.title}}</option>
                        {% endfor %}
                    </select> <br><br>
            Question Description: <input type="text" name="question_desc" value=""><br><br>
            Image: <input type="file" name="question_img" value=""><br><br>
            <input type="hidden" name="question_votes" value=0>
            <input type="submit" name="" value="submit">
        </form>
    </body>
</html>

qna_app/templates/questions.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        {% for question in questions %}
            <h1>{{question.title}}</h1>
            <br>
            <h2>{{question.question_desc}}</h2>
            <br>
            <img src="../../media/{{question.question_img}}" alt="">
        {% endfor %}
    </body>
</html>

user_app/templates/login.html
{%extends 'base.html'%}

    {% block main_content %}
        <form action="" method="POST">
            {% csrf_token %}
        <div class="login text-center">
        <h1>Login to your account</h1></div><br>
      Email:<br>
      <input type="text" class="form-control" name="email">
      <br>
      Password:<br>
      <input type="password" class="form-control" name="pass">
      <!-- <small><a href="#">Forgot password</a></small> -->
      <br><br>
        <button type="submit" name="login" class="btn btn-success">Login</button>
    </form>
    {% endblock %}